# version: '3.8'

services:
  # 1. Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: music-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: musicdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - music-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d musicdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Object Storage (MinIO)
  minio:
    image: minio/minio:latest
    container_name: music-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Console Web UI
    volumes:
      - minio_data:/data
    networks:
      - music-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # 3. Setup AutomÃ¡tico do MinIO (Cria o bucket ao iniciar)

  minio-setup:
    image: minio/mc
    container_name: music-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_USER: minioadmin
      MINIO_PASS: minioadmin
      BUCKET_NAME: music-covers
    entrypoint: >
      /bin/sh -c "
      until mc alias set myminio http://$${MINIO_HOST}:$${MINIO_PORT} $${MINIO_USER} $${MINIO_PASS}; do
        echo 'Waiting for MinIO...'
        sleep 1
      done;
      mc mb myminio/$${BUCKET_NAME} --ignore-existing;
      echo 'Bucket $${BUCKET_NAME} created successfully';
      exit 0;
      "
    networks:
      - music-net

volumes:
  postgres_data:
  minio_data:

networks:
  music-net:
    driver: bridge