server:
  port: 8080

spring:
  application:
    name: music-catalog

  # Configuração do Banco de Dados
  datasource:
    url: jdbc:postgresql://localhost:5432/musicdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: music-catalog-pool
      maximum-pool-size: 10
      minimum-idle: 5

  # JPA e Hibernate
  jpa:
    open-in-view: false # Desabilita OSIV para evitar problemas de performance e conexões presas
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate # Garante que o Hibernate valide o schema criado pelo Flyway, sem alterá-lo

  # Versionamento de Banco de Dados
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Configuração de Upload
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Configurações Personalizadas (MinIO / Storage)
app:
  storage:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: music-covers
    region: us-east-1